// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0--rc1
// source: mutual.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int32                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMessage) Reset() {
	*x = RequestMessage{}
	mi := &file_mutual_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMessage) ProtoMessage() {}

func (x *RequestMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mutual_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMessage.ProtoReflect.Descriptor instead.
func (*RequestMessage) Descriptor() ([]byte, []int) {
	return file_mutual_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestMessage) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReplyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMessage) Reset() {
	*x = ReplyMessage{}
	mi := &file_mutual_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMessage) ProtoMessage() {}

func (x *ReplyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mutual_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMessage.ProtoReflect.Descriptor instead.
func (*ReplyMessage) Descriptor() ([]byte, []int) {
	return file_mutual_proto_rawDescGZIP(), []int{1}
}

func (x *ReplyMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_mutual_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_mutual_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_mutual_proto_rawDescGZIP(), []int{2}
}

var File_mutual_proto protoreflect.FileDescriptor

const file_mutual_proto_rawDesc = "" +
	"\n" +
	"\fmutual.proto\x12\x06mutual\">\n" +
	"\x0eRequestMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x05R\ttimestamp\"\x1e\n" +
	"\fReplyMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x05\n" +
	"\x03Ack2y\n" +
	"\x0fMutualExclusion\x124\n" +
	"\rRequestAccess\x12\x16.mutual.RequestMessage\x1a\v.mutual.Ack\x120\n" +
	"\vReplyAccess\x12\x14.mutual.ReplyMessage\x1a\v.mutual.AckBAZ?github.com/ErolEskici/Mandatory-Activity-4/node/src/proto;protob\x06proto3"

var (
	file_mutual_proto_rawDescOnce sync.Once
	file_mutual_proto_rawDescData []byte
)

func file_mutual_proto_rawDescGZIP() []byte {
	file_mutual_proto_rawDescOnce.Do(func() {
		file_mutual_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mutual_proto_rawDesc), len(file_mutual_proto_rawDesc)))
	})
	return file_mutual_proto_rawDescData
}

var file_mutual_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mutual_proto_goTypes = []any{
	(*RequestMessage)(nil), // 0: mutual.RequestMessage
	(*ReplyMessage)(nil),   // 1: mutual.ReplyMessage
	(*Ack)(nil),            // 2: mutual.Ack
}
var file_mutual_proto_depIdxs = []int32{
	0, // 0: mutual.MutualExclusion.RequestAccess:input_type -> mutual.RequestMessage
	1, // 1: mutual.MutualExclusion.ReplyAccess:input_type -> mutual.ReplyMessage
	2, // 2: mutual.MutualExclusion.RequestAccess:output_type -> mutual.Ack
	2, // 3: mutual.MutualExclusion.ReplyAccess:output_type -> mutual.Ack
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mutual_proto_init() }
func file_mutual_proto_init() {
	if File_mutual_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mutual_proto_rawDesc), len(file_mutual_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mutual_proto_goTypes,
		DependencyIndexes: file_mutual_proto_depIdxs,
		MessageInfos:      file_mutual_proto_msgTypes,
	}.Build()
	File_mutual_proto = out.File
	file_mutual_proto_goTypes = nil
	file_mutual_proto_depIdxs = nil
}
